version: 2.1

orbs:
  react-native: react-native-community/react-native@4.4.2

commands:
  checkout-attach-workspace:
    description: "Checkout and attach workspace"
    steps:
      - checkout
      - attach_workspace:
          at: ~/app

jobs:
  install-dependencies:
    executor: react-native/linux_js
    working_directory: ~/app
    steps:
      - checkout
      - react-native/yarn_install
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  lint:
    executor: react-native/linux_js
    working_directory: ~/app
    steps:
      - checkout-attach-workspace
      - run:
          name: Lint
          command: yarn lint

  validate-flow:
    executor: react-native/linux_js
    working_directory: ~/app
    steps:
      - checkout-attach-workspace
      - run:
          name: Flow
          command: yarn validate:flow

  ios_build:
    macos:
      xcode: 11.5.0
    working_directory: ~/app
    steps:
      - checkout
      - react-native/setup_macos_executor
      - run: yarn install --frozen-lockfile --non-interactive
      - react-native/pod_install:
          pod_install_directory: ./example/ios
      - react-native/ios_build:
          project_path: ./example/ios/Example.xcworkspace
          project_type: workspace
          scheme: example
          device: iPhone 11

  publish-version:
    executor: react-native/linux_js
    working_directory: ~/app
    steps:
      - checkout-attach-workspace
      - run:
          name: Publish New Version
          command: yarn ci:publish

  deploy-docs:
    executor: react-native/linux_js
    working_directory: ~/app
    steps:
      - checkout-attach-workspace
      - run:
          name: Deploying new docs-version
          command: |
            git config --global user.email "${GH_EMAIL}@users.noreply.github.com"
            git config --global user.name "${GH_NAME}"
            echo "machine github.com login $GH_NAME password $GH_TOKEN" > ~/.netrc
            cd website && yarn install && CUSTOM_COMMIT_MESSAGE="[skip ci]" GIT_USER=${GH_NAME} yarn deploy

workflows:
  version: 2

  build-lint-app:
    jobs:
      - install-dependencies:
          context: wealthsimple
          filters:
            branches:
              ignore:
                - master
      - react-native/android_build:
          context: wealthsimple
          checkout: true
          project_path: ./example/android
          workspace_root: ~/app
          filters:
            branches:
              ignore:
                - master
      - ios_build:
          context: wealthsimple
          filters:
            branches:
              ignore:
                - master
      - lint:
          context: wealthsimple
          requires:
            - install-dependencies
      - validate-flow:
          context: wealthsimple
          requires:
            - install-dependencies

  release:
    jobs:
      - install-dependencies:
          context: wealthsimple
          filters:
            branches:
              only:
                - master
      - publish-version:
          context: wealthsimple
          requires:
            - install-dependencies
      - deploy-docs:
          context: wealthsimple
          filters:
            branches:
              only:
                - master
